# Golang CircleCI 2.0 configuration file
version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: export GOPATH=$PWD && echo "$GOPATH $PWD" && go test topten unpacker -v

workflows:
  version: 2
  test_app:
    jobs:
      - test:
          filters:
            branches:
              only:
                - cli
