# Golang CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    branches:
      only:
        - top-ten
  build-go1.12:
    docker:
      - image: circleci/golang:1.12
    steps:
      - run: go test -v

workflows:
  version: 2
  build_and_test:
  jobs:
    - build-go1.12
